name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/cache@v4
        with:
         path: '**/node_modules'
         key: ${{ runner.os }}-build-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-scripts
      - run: yarn run build

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-deploy-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn install --ignore-scripts
      - run: yarn run build
      - run: rm .gitignore
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
